osx_image: xcode8

language:  swift

xcode_project: MYJSON.xcodeproj

branches:
  only:
  - master

env:
  global:
  - FRAMEWORK_NAME = MYJSON
  - USER_NAME = damonthecricket
  - REPO_NAME = my-json

script:
- travis_retry xcodebuild -project MYJSON.xcodeproj/ -scheme "MYJSON-iOS" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty
- travis_retry xcodebuild -project MYJSON.xcodeproj/ -scheme "MYJSON-macOS" build-for-testing test | xcpretty
- travis_retry xcodebuild -project MYJSON.xcodeproj/ -scheme "MYJSON-tvOS" -destination "platform=tvOS Simulator,name=Apple TV 1080p" build-for-testing test | xcpretty
- travis_retry xcodebuild -project MYJSON.xcodeproj/ -scheme "MYJSON-watchOS" -destination "platform=watchOS Simulator,name=Apple Watch Series 2 - 42mm" build-for-testing test | xcpretty